spring.application.name=backend

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Email SMTP Configuration (for sending replies)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aman.yadav.st.johns@gmail.com
spring.mail.password=mdye uetz jiry vzcy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email IMAP Configuration (for receiving tickets)
app.email.imap.host=imap.gmail.com
app.email.imap.port=993
app.email.imap.username=aman.yadav.st.johns@gmail.com
app.email.imap.password=mdye uetz jiry vzcy
app.email.imap.protocol=imaps